name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
    - name: Build and push Docker image
      run: |
          IMAGE_TAG=$(date +%s)
          docker build . --file Dockerfile --tag delaroth/docker-flask:$IMAGE_TAG
          docker push delaroth/docker-flask:$IMAGE_TAG
      
